name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
  workflow_dispatch:

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './apps/api'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
            with:
              fetch-depth: 0  # Fetch full git history for commit SHA

          - name: 'Set up Docker Buildx'
            uses: docker/setup-buildx-action@v3

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and Push Image'
            uses: docker/build-push-action@v6
            with:
              context: ./apps/api
              push: true
              tags: |
                ghcr.io/firecrawl/firecrawl:latest
                ghcr.io/firecrawl/firecrawl:${{ github.sha }}
              cache-from: type=registry,ref=ghcr.io/firecrawl/firecrawl:buildcache
              cache-to: type=registry,ref=ghcr.io/firecrawl/firecrawl:buildcache,mode=max
              build-args: |
                COMMIT_SHA=${{ github.sha }}
                SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
                SENTRY_ORG=${{ secrets.SENTRY_ORG }}
                SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
